version: "2.23"

services:
  app:
    image: university-platform
    container_name: university-platform
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/

  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=universityPlatform
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27018:27017