http:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s

logger:
  level: 5

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 43200m

cache:
  ttl: 3600s

email:
  provider: smtp.gmail.com
  port: 587
