# TODO Все значения, несущие информацию в app.env файл, имена, пароли и тд
# TODO Точно также переработать тест + фикстура

http:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s

logger:
  level: 10

mongo:
  databaseName: universityPlatform

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 43200m